// LOCALHOST

// swagger ui
GET http://localhost:8080/api-docs

// Grab everything
GET http://localhost:8080/toDO
###

// grab "scripture study" to do item
GET http://localhost:8080/toDO/628503d55174de64e4e9b7a1
###

// grab "change my contacts" to do item
GET http://localhost:8080/toDO/628503d55174de64e4e9b7a2

###

// grab "phone bill" to do item
GET http://localhost:8080/toDO/628503d55174de64e4e9b7a3

###

// add a new item
POST http://localhost:8080/toDO HTTP/1.1
content-type: application/json
{
    "title": "Turn in homework",
    "date": "05/21/2022",
    "time": "11:59PM",
    "place": "School",
    "description": "turn in homework for CSE341.",
    "completed": false
}

###
// update an item in "scripture study"
PUT http://localhost:8080/toDO/628503d55174de64e4e9b7a1 HTTP/1.1
content-type: application/json
{
    "title": "Scripture Study",
    "date": "05/30/2022",
    "time": "10:00AM",
    "place": "School",
    "description": "Complete Book of Mormon scripture study.",
    "completed": false
}

###
// PRODUCTION Deploy

// swagger ui
GET https://cse341-w05-w08.herokuapp.com/api-docs

###

// Grab everything
GET https://cse341-w05-w08.herokuapp.com/toDo

###

// Grab an indiviual item
GET https://cse341-w05-w08.herokuapp.com/toDo/628503d55174de64e4e9b7a2

###

// add a new item
POST https://cse341-w05-w08.herokuapp.com/toDo HTTP/1.1
content-type: application/json
{
    "title": "Do Laundry",
    "date": "05/25/2022",
    "time": "10:59AM",
    "place": "Home",
    "description": "Do laundry at some point today.",
    "completed": true
}

###

// update an item in "phone bill"
PUT https://cse341-w05-w08.herokuapp.com/toDo/628503d55174de64e4e9b7a3 HTTP/1.1
content-type: application/json
{
    "title": "Phone Bill",
    "date": "07/18/2022",
    "time": "8:00PM",
    "place": "Apartment",
    "description": "Send Venmo amount to Dad for phone bill",
    "completed": false
}